version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app

permissions:
  - object: /
    owner: ec2-user
    group: ec2-user
    type:
      - directory

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/run.sh
      runas: ec2-user
  ValidateService:
    - location: scripts/check_deployment.sh
      runas: ec2-user
