version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app

permissions:
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777
    type:
      - file

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/run.sh
      runas: ec2-user
